# sandman_config/config.yml

# Global settings for the entire Sandman Orchestrator
settings:
  debug: false
  md_output_directory: "workspace/feeds/"
  md_log: "workspace/feeds/log.md"
  json_output_directory: "workspace/data/"
  group_by_module: true
  group_by_source: true
  min_age_hours: 12
  max_results: 8
  enable_md_log: true

# The Routine: Default queue of tasks to be executed in order
routine:
  - name: "Daily MarvelStudiosSpoilers Updates"
    module: "reddit"
    source: "MarvelStudiosSpoilers"
    max_results: 3
    detail: "MD"
    min_score: 10
    sort: "new"
    group_by_source: true

  - name: "Daily Comic-related LeaksUpdates"
    module: "reddit"
    source: "LeaksAndRumors"
    max_results: 3
    detail: "MD"
    label: "comics"
    min_score: 10
    sort: "new"
    group_by_source: true
    
  - name: "UX Ops Remote Search"
    module: "jobs"
    query: "software engineer"
    location: "Remote"
    salary_min: 120000
    is_remote: true
    max_results: 20
    sources: ["indeed", "zip_recruiter", "google"]
